[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "safestep"
version = "0.1.0"
description = "SafeStep backend"
requires-python = ">=3.11"
dependencies = [
    "boto3",
]

[tool.setuptools.packages.find]
include = ["backend*"]

[tool.ruff.lint]
ignore = ["I001"]