"""add unique refresh token hash

Revision ID: 46d34abb3b93
Revises: e7bcceb9ad39
Create Date: 2026-09-19 19:58:08.720851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d34abb3b93'
down_revision: Union[str, Sequence[str], None] = 'e7bcceb9ad39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
    "uq_sessions_refresh_token_hash",
    "sessions",
    ["refresh_token_hash"],
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    "uq_sessions_refresh_token_hash",
    "sessions",
    type_="unique",
)
    # ### end Alembic commands ###
